### ISSUE TITLE
Can't import pip.venv

### ISSUE THREAD

**Issue by stuaxo** [wil/pip-proxy#1]
When I try and run pipp I get the following error

(pipp)nickb@intdev:~/projects/pip-proxy$ ./pipp
Traceback (most recent call last):
  File "./pipp", line 9, in <module>
    main.main()
  File "/home/nickb/projects/pip-proxy/pipproxy/pippatch/main.py", line 51, in main
    import pip.venv
ImportError: No module named venv

(ubuntu, python 2.6)

**Comment by wil** [comment]
The `pipp` script was indeed meant to work as a replacement for `pip`, but at the moment it's not working.

What's working is the wsgi pip proxy server, and I've just added some instructions on how to use it in the README.

Your pip version is likely too old. Check that it's at least 1.0.
